# Generated by Django 2.1.1 on 2022-03-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20220304_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='pending_deposit',
            field=models.IntegerField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(blank=True, default='pending', max_length=100),
        ),
    ]
