# Generated by Django 2.1.1 on 2022-03-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_auto_20220307_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='pending_withdrawal',
            field=models.IntegerField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(default='Congratulations! You just received $(amount) from your investment with us. your trade cycle is in progress.', max_length=200),
        ),
    ]
