# Generated by Django 2.1.1 on 2022-03-08 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_auto_20220307_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='restricted',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
