# Generated by Django 2.1.1 on 2022-03-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_balance_restricted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='name',
            new_name='admin_details',
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(default='Congratulations! You just received $0 from your investment with us. your trade cycle is in progress.', max_length=200),
        ),
    ]
